"""
Partition-sensitivity study for the AE98 replication (replication_ae98.py),
mirroring replication_ak91_sensitivity.py: B independent random permutations
of the data, each shared by every MoM-based procedure, for each of the five
Table 5 outcomes (Y varies; X = morekids and Z = samesex are common, so the
same B permutations are reused across outcomes, keeping partitions aligned).

Here, unlike AK91, the finite-sample strength conditions of the point
estimators HOLD (binary X and Z bound the moments), so partition noise is
expected to be far smaller relative to sampling noise.

Outputs:
    Paper/images/graphs/ae98_seed_sensitivity_<outcome>.png   (per outcome)
    Paper/iteration4/ae98_sensitivity.tex
    Code/output/ae98_sensitivity_seeds.csv

Usage:
    python replication_ae98_sensitivity.py [--reps 1000] [--seed 1998]
                                           [--delta 0.05] [--jobs -1]
"""
from __future__ import annotations

import argparse
import time

import numpy as np
import pandas as pd
from joblib import Parallel, delayed

import inference as inf
from replication_ae98 import OUTCOMES, ROOT, build_sample, replicate_table5, to_iv_frame
from replication_ak91_sensitivity import GRAPHS_DIR, make_figure, one_partition, summarise

CSV_PATH = ROOT / "Code" / "output" / "ae98_sensitivity_seeds.csv"
TEX_PATH = ROOT / "Paper" / "iteration4" / "ae98_sensitivity.tex"


def ar_reference(iv_df: pd.DataFrame, delta: float, ols_beta: float) -> dict:
    """Partition-free standard AR test summary for one outcome."""
    ar_cs = inf.standard_ar_cs(iv_df, delta=delta)
    ar_test = inf.standard_ar_test(iv_df, np.array([0.0, ols_beta]), delta=delta)
    return dict(
        rej0=bool(ar_test["reject"][0]), rejOLS=bool(ar_test["reject"][1]),
        split=len(ar_cs) > 1,
        unbounded=any(np.isinf(lo) or np.isinf(hi) for lo, hi in ar_cs),
        length=float(sum(hi - lo for lo, hi in ar_cs)),
    )


def write_tex(tables: dict, B: int) -> None:
    lines = [
        "% Auto-generated by Code/replication_ae98_sensitivity.py -- do not edit by hand.",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Partition sensitivity on the AE98 1980 all-women sample: "
        f"$B = {B:,}$".replace(",", r"{,}") +
        r" random partitions shared by all MoM-based procedures and reused"
        r" across outcomes ($\delta = 0.05$). For each outcome, the top rows"
        r" give the dispersion of the partition-dependent point estimates"
        r" (the partition-free Wald estimate in the label); the bottom rows"
        r" give rejection and shape frequencies of the 95\% confidence sets."
        r" The standard AR test is partition-free and shown for reference.}",
        r"\label{tab:ae98_sensitivity}",
        r"\small",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"Outcome & Estimator & Mean & SD & Q$_{0.05}$ & Q$_{0.95}$ & \\",
        r"\midrule",
    ]
    for key, (label, wald, est_tab, _) in tables.items():
        dp = 1 if key == "incomem" else 4
        for i, (_, r) in enumerate(est_tab.iterrows()):
            head = f"{label} (Wald {wald:.{dp}f})" if i == 0 else ""
            lines.append(
                f"{head} & {r['estimator']} & {r['mean']:.{dp}f} & {r['sd']:.{dp}f} & "
                f"{r['q05']:.{dp}f} & {r['q95']:.{dp}f} & \\\\"
            )
    lines += [
        r"\midrule",
        r"Outcome & Test & \% rej.\ $\beta_0{=}0$ & \% rej.\ $\beta_0{=}\beta_{\mathrm{OLS}}$ & "
        r"\% split & \% unb. & Med.\ len. \\",
        r"\midrule",
    ]
    for key, (label, wald, _, freq_tab) in tables.items():
        dp = 0 if key == "incomem" else 3
        for i, (_, r) in enumerate(freq_tab.iterrows()):
            head = label if i == 0 else ""
            ln = "$\\infty$" if np.isinf(r["median_length"]) else f"{r['median_length']:.{dp}f}"
            lines.append(
                f"{head} & {r['test']} & {r['pct_reject_zero']:.1f} & "
                f"{r['pct_reject_ols']:.1f} & {r['pct_split']:.1f} & "
                f"{r['pct_unbounded']:.1f} & {ln} \\\\"
            )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    TEX_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TEX_PATH}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("--reps", type=int, default=1000)
    p.add_argument("--seed", type=int, default=1998)
    p.add_argument("--delta", type=float, default=0.05)
    p.add_argument("--jobs", type=int, default=-1)
    args = p.parse_args()

    d = build_sample()
    rep = replicate_table5(d)
    k = inf.k_blocks(args.delta)
    c_crit = inf.rk_critical_value(k, args.delta)

    all_rows: list[pd.DataFrame] = []
    tables: dict = {}
    for key, label in OUTCOMES.items():
        iv_df = to_iv_frame(d, key)
        Y = iv_df["Y"].to_numpy()
        X = iv_df["X"].to_numpy()
        Z = iv_df["Z"].to_numpy()
        wald = rep[f"{key}_wald"][0]
        ols = rep[f"{key}_ols"]
        ar_ref = ar_reference(iv_df, args.delta, ols)

        t0 = time.time()
        rows = Parallel(n_jobs=args.jobs, verbose=0)(
            delayed(one_partition)(Y, X, Z, (args.seed, i), args.delta, ols, c_crit)
            for i in range(args.reps)
        )
        res = pd.DataFrame(rows)
        print(f"{label}: {args.reps} partitions in {time.time() - t0:.0f}s")

        est_tab, freq_tab = summarise(res, wald, ols, ar_ref)
        print(est_tab.to_string(index=False, float_format=lambda v: f"{v:.4f}"))
        print(freq_tab.to_string(index=False, float_format=lambda v: f"{v:.2f}"))
        make_figure(res, wald, ols,
                    out_path=GRAPHS_DIR / f"ae98_seed_sensitivity_{key}.png")
        tables[key] = (label, wald, est_tab, freq_tab)
        res.insert(0, "outcome", key)
        all_rows.append(res)

    CSV_PATH.parent.mkdir(exist_ok=True)
    pd.concat(all_rows, ignore_index=True).to_csv(CSV_PATH, index=False)
    print(f"wrote {CSV_PATH}")
    write_tex(tables, args.reps)


if __name__ == "__main__":
    main()
